### ISSUE TITLE
BUG: The condition function can't be async

### ISSUE THREAD

**Issue by farling42** [MiahNelah/better-entity-link#12]
Although the callback can be async, the condition is not async.

I know this will cause problems with trying to access contents of packs, but core Foundry expects the condition function to directly return a truthy rather than a Promise.

**Comment by MiahNelah** [comment]
I see async condition nowhere... What's your module version ?

**Comment by farling42** [comment]
Here, https://github.com/MiahNelah/better-entity-link/blob/54c43757e7c1cefcd3dd95eedc6f4147c609d110/module/src/BetterEntityLink.js#L100

**Comment by MiahNelah** [comment]
Oh yeah, the most critical one. Unfortunatly you're true, this is a issue I faced : there is no sync methods to access compendium data at all. One solution may be to load indexes of all compendiums, but I really don't want to do this because of performance issues.
I'm afraid I'll need to limit condition check to user's permissions validation.

**Comment by MiahNelah** [comment]
I rewrote condition handling and updated all actions. Now, condition have only access to document if loaded in world, or indexed-only data. It's more limited but enough for most actions. I release an update v1.3.

**Comment by farling42** [comment]
That looks good.
I hope that core Foundry will make it a sync soon, so that we can access compendiums more easily.
